<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Login_Regression" duration-ms="37559" started-at="2020-06-12T13:54:17 PDT" finished-at="2020-06-12T13:54:55 PDT">
    <groups>
    </groups>
    <test name="Login_ValidData" duration-ms="15046" started-at="2020-06-12T13:54:17 PDT" finished-at="2020-06-12T13:54:32 PDT">
      <class name="com.salesforce.TC1_SFDC_LoginValid">
        <test-method status="PASS" signature="TC1ValidCresentials(java.lang.String, java.lang.String)[pri:0, instance:com.salesforce.TC1_SFDC_LoginValid@4493d195]" name="TC1ValidCresentials" duration-ms="2403" started-at="2020-06-12T13:54:18 PDT" data-provider="LoginCredentials" finished-at="2020-06-12T13:54:20 PDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[mitali.k@salesforce.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test@123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC1ValidCresentials -->
        <test-method status="PASS" signature="logoutURL()[pri:0, instance:com.salesforce.TC1_SFDC_LoginValid@4493d195]" name="logoutURL" is-config="true" duration-ms="12145" started-at="2020-06-12T13:54:20 PDT" finished-at="2020-06-12T13:54:32 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutURL -->
      </class> <!-- com.salesforce.TC1_SFDC_LoginValid -->
    </test> <!-- Login_ValidData -->
    <test name="Login_InvalidData" duration-ms="9420" started-at="2020-06-12T13:54:33 PDT" finished-at="2020-06-12T13:54:42 PDT">
      <class name="com.salesforce.TC2_SFDC_LoginInvalid">
        <test-method status="FAIL" signature="TC1InValidCresentials(java.lang.String, java.lang.String)[pri:1, instance:com.salesforce.TC2_SFDC_LoginInvalid@2353b3e6]" name="TC1InValidCresentials" duration-ms="5076" started-at="2020-06-12T13:54:33 PDT" data-provider="LoginCredentials" finished-at="2020-06-12T13:54:38 PDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[mitali.k@salesforce.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Please enter your password.> but was:<true>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Please enter your password.> but was:<true>
at org.testng.AssertJUnit.fail(AssertJUnit.java:47)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:330)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:66)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:71)
at com.salesforce.TC2_SFDC_LoginInvalid.TC1InValidCresentials(TC2_SFDC_LoginInvalid.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC1InValidCresentials -->
        <test-method status="FAIL" signature="TC1InValidCresentials(java.lang.String, java.lang.String)[pri:1, instance:com.salesforce.TC2_SFDC_LoginInvalid@2353b3e6]" name="TC1InValidCresentials" duration-ms="4332" started-at="2020-06-12T13:54:38 PDT" data-provider="LoginCredentials" finished-at="2020-06-12T13:54:42 PDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[123.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[22131.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Please check your username and password. If you still can't log in, contact your Salesforce administrator.> but was:<true>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Please check your username and password. If you still can't log in, contact your Salesforce administrator.> but was:<true>
at org.testng.AssertJUnit.fail(AssertJUnit.java:47)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:330)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:66)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:71)
at com.salesforce.TC2_SFDC_LoginInvalid.TC1InValidCresentials(TC2_SFDC_LoginInvalid.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC1InValidCresentials -->
      </class> <!-- com.salesforce.TC2_SFDC_LoginInvalid -->
    </test> <!-- Login_InvalidData -->
    <test name="Login_RememeberMe" duration-ms="13017" started-at="2020-06-12T13:54:42 PDT" finished-at="2020-06-12T13:54:55 PDT">
      <class name="com.salesforce.TC1_SFDC_LoginValid">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:com.salesforce.TC1_SFDC_LoginValid@4493d195]" name="launchBrowser" is-config="true" duration-ms="6970" started-at="2020-06-12T13:54:03 PDT" finished-at="2020-06-12T13:54:10 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="quitbrowser()[pri:0, instance:com.salesforce.TC1_SFDC_LoginValid@4493d195]" name="quitbrowser" is-config="true" duration-ms="245" started-at="2020-06-12T13:54:55 PDT" finished-at="2020-06-12T13:54:55 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitbrowser -->
      </class> <!-- com.salesforce.TC1_SFDC_LoginValid -->
      <class name="com.salesforce.TC3_SFDC_LoginRemeberMe">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:com.salesforce.TC3_SFDC_LoginRemeberMe@1a1d6a08]" name="launchBrowser" is-config="true" duration-ms="3903" started-at="2020-06-12T13:54:14 PDT" finished-at="2020-06-12T13:54:17 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="TC2RememenerMe(java.lang.String, java.lang.String)[pri:1, instance:com.salesforce.TC3_SFDC_LoginRemeberMe@1a1d6a08]" name="TC2RememenerMe" duration-ms="13011" started-at="2020-06-12T13:54:42 PDT" data-provider="LoginCredentials" finished-at="2020-06-12T13:54:55 PDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[mitali.k@salesforce.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test@123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC2RememenerMe -->
        <test-method status="PASS" signature="quitbrowser()[pri:0, instance:com.salesforce.TC3_SFDC_LoginRemeberMe@1a1d6a08]" name="quitbrowser" is-config="true" duration-ms="0" started-at="2020-06-12T13:54:55 PDT" finished-at="2020-06-12T13:54:55 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitbrowser -->
      </class> <!-- com.salesforce.TC3_SFDC_LoginRemeberMe -->
      <class name="com.salesforce.TC2_SFDC_LoginInvalid">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:com.salesforce.TC2_SFDC_LoginInvalid@2353b3e6]" name="launchBrowser" is-config="true" duration-ms="3475" started-at="2020-06-12T13:54:10 PDT" finished-at="2020-06-12T13:54:14 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="quitbrowser()[pri:0, instance:com.salesforce.TC2_SFDC_LoginInvalid@2353b3e6]" name="quitbrowser" is-config="true" duration-ms="1" started-at="2020-06-12T13:54:55 PDT" finished-at="2020-06-12T13:54:55 PDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitbrowser -->
      </class> <!-- com.salesforce.TC2_SFDC_LoginInvalid -->
    </test> <!-- Login_RememeberMe -->
  </suite> <!-- Login_Regression -->
</testng-results>
